### ISSUE TITLE
12 hour times instead of 24 hour

### ISSUE THREAD

**Issue by josephshepin** [PrairieLearn/PrairieTest-feedback#29]
I find it much easier to read 12 hour times instead of 24 hour times and I think we should be able to have that option in settings, or just default to 12 hour time because that's what almost all websites do by default.

**Comment by wadefagen** [comment]
+1 to this.

We just sent through course feedback for n=750 students, and probably ~90% of all no-contact missed exams over a few semesters were students confusing "20:00" with "10:00pm" (instead of 8:00pm) or similar incorrect conversions.  These types of time mistakes impacted both weaker students and students from underrepresented groups disproportionately more than others (all but one was in from my gened course; non-engineers appear to struggle with this more than engineers).  The impact of missing an exam was an incredibly stressful situation to the student resulting in their increased frustration with the PT/PL system and a lower satisfaction with the course as a whole.

**Comment by JosephShepin** [comment]
Thank you for this insightful data. In a more informal survey conducted on Reddit, students significantly preferred 12 hour time shown by the results of this poll. Reddit likely _overrepresents_ engineering majors which makes the argument for 12 hour time even more compelling because engineers tend to prefer 24 hour time.

<img width="674" alt="Screenshot 2023-06-03 at 7 41 05 PM" src="https://github.com/PrairieLearn/PrairieTest-feedback/assets/31457361/a328f5e5-928b-46bd-a774-de7030a85435">

**Comment by JosephShepin** [comment]
@mwest1066 Is this issue going to get addressed?

**Comment by nwalters512** [comment]
This change was just deployed! https://github.com/PrairieLearn/PrairieLearn/discussions/9684

**Comment by josephshepin** [comment]
@nwalters512  You are a hero!

**Comment by nwalters512** [comment]
All credit goes to @mwest1066 for implementing this!

**Comment by josephshepin** [comment]
@mwest1066 you are a hero!
